name: The lake on fire
favicon: null
layout_spectrum: 0.3701243819668889
typography_spectrum: 0.4266548827290535
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010302'
    - '#154551'
    - '#ffffff'
    - '#798d8c'
    - '#c3a37d'
  brandStrength: 0.875
  lightness: 0
  saturation: 0.9375
  rhythmicContrast: 0.25
purpose: []
