name: The lake on fire
favicon: null
layout_spectrum: 1
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010302'
    - '#22505b'
    - '#ffffff'
    - '#b4a189'
    - '#f2c184'
  brandStrength: 0.8125
  lightness: 0
  saturation: 0.875
  rhythmicContrast: 0
purpose: []
