name: The lake on fire
favicon: null
layout_spectrum: 0
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c1c1c'
    - '#246e8f'
    - '#ff5742'
    - '#c0c8c5'
    - '#6a9fb0'
  brandStrength: 0.6875
  lightness: 0
  saturation: 0.875
  rhythmicContrast: 0
purpose: []
