name: The lake on fire
favicon: null
layout_spectrum: 0.25862
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#040e0f'
    - '#444444'
    - '#1f1812'
    - '#442d1a'
  brandStrength: 0.8125
  lightness: 0
  saturation: 0.9375
  rhythmicContrast: 0.25
purpose: []
