name: The lake on fire
favicon: null
layout_spectrum: 0.4841
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#256d8f'
    - '#10365b'
    - '#b2cbd7'
    - '#84acbf'
  brandStrength: 1
  lightness: 0.1875
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
